apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pp-ci
spec:
  description: |
      This pipeline contains ci tasks - clone, check repo, image build. The
      dependency is:
                  git-clone
              /               \
        cat-readme           build-image
  workspaces:
    - name: shared
  params:
    - name: git-repo
      description: the source repo to clone
    - name: git-revision
      description: the revision of the source repo
    - name: IMAGE
      description: Name (reference) of the image to build.
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
  results:
    - name: CHAINS-GIT_URL
      description: Git URL that the source repo containing Dockerfile is fetched from
      value: $(tasks.git-clone.results.url)
    - name: CHAINS-GIT_COMMIT
      description: Git commit sha of the source repo containing Dockerfile
      value: $(tasks.git-clone.results.commit)
    - name: IMAGE_DIGEST
      description: Digest of the image just built by the pipeline.
      value: $(tasks.build-image.results.IMAGE_DIGEST)
    - name: IMAGE_URL
      description: URL of the image just built by the pipeline.
      value: $(tasks.build-image.results.IMAGE_URL)
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-repo)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog
          - name: revision
            value: main
          - name: pathInRepo
            value: task/git-clone/0.7/git-clone.yaml
    - name: cat-readme
      runAfter: ["git-clone"]
      workspaces:
      - name: source
        workspace: shared
      taskSpec:
        workspaces:
        - name: source
        steps:
        - name: echo-readme
          image: zshusers/zsh:4.3.15
          script: |
            #!/usr/bin/env zsh
            cat $(workspaces.source.path)/README.md
    - name: build-image
      runAfter: ["git-clone"]
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: shared
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog
          - name: revision
            value: main
          - name: pathInRepo
            value: task/kaniko/0.6/kaniko.yaml
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pr-ci
spec:
  serviceAccountName: myksa
  params:
    - name: git-repo
      value: https://github.com/chuangw6/tekton-test
    - name: git-revision
      value: main
    - name: IMAGE
      value: us-central1-docker.pkg.dev/chuangw-test/kaniko-example/ci
  pipelineRef:
    name: pp-ci
  workspaces:
    - name: shared
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
