apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: simple-taskrun
spec:
  taskSpec:
    params:
      - name: username
        default: "xxx"
    steps:
      - image: alpine:3.15
        script: |
          echo "hello $(params.username)"
