
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: a-simple-task
spec:
  params:
  - name: username
    default: "xxx"
  steps:
  - image: alpine:3.15
    script: |
      echo "hello $(params.username)"
